services:
  - type: web
    name: hotel-booking-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hotel_booking_system.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hotel_booking_system.settings
