services:
  - type: web
    name: hotel-booking-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hotel_project.wsgi:application"
    workingDir: hotel_booking_system   # ✅ Added this line
